module.exports = {
  __type__: "Deck",
  children: [],
  crowdanki_uuid: "93df2c1f-ac3c-11ed-97c2-b48c9d0220f8",
  deck_config_uuid: "6476e26d-ac38-11ed-822a-b48c9d0220f8",
  deck_configurations: [
    {
      __type__: "DeckConfig",
      autoplay: true,
      buryInterdayLearning: false,
      crowdanki_uuid: "6476e26d-ac38-11ed-822a-b48c9d0220f8",
      dyn: false,
      interdayLearningMix: 0,
      lapse: {
        delays: [10.0],
        leechAction: 1,
        leechFails: 8,
        minInt: 1,
        mult: 0.0,
      },
      maxTaken: 60,
      name: "Default",
      new: {
        bury: false,
        delays: [1.0, 10.0],
        initialFactor: 2500,
        ints: [1, 4, 0],
        order: 1,
        perDay: 20,
      },
      newGatherPriority: 0,
      newMix: 0,
      newPerDayMinimum: 0,
      newSortOrder: 0,
      replayq: true,
      rev: {
        bury: false,
        ease4: 1.3,
        hardFactor: 1.2,
        ivlFct: 1.0,
        maxIvl: 36500,
        perDay: 200,
      },
      reviewOrder: 0,
      timer: 0,
    },
  ],
  desc: "",
  dyn: 0,
  extendNew: 0,
  extendRev: 0,
  media_files: [],
  name: "Chem: Definitions",
  note_models: [
    {
      __type__: "NoteModel",
      crowdanki_uuid: "65b70b2f-7697-11ed-9d99-b48c9d0220f8",
      css: ".card {\n  font-family: arial;\n  font-size: 20px;\n  text-align: center;\n  color: black;\n  background-color: white;\n}\n",
      flds: [
        {
          description: "",
          font: "Arial",
          name: "Front",
          ord: 0,
          rtl: false,
          size: 20,
          sticky: false,
        },
        {
          description: "",
          font: "Arial",
          name: "Back",
          ord: 1,
          rtl: false,
          size: 20,
          sticky: false,
        },
      ],
      latexPost: "\\end{document}",
      latexPre:
        "\\documentclass[12pt]{article}\n\\special{papersize=3in,5in}\n\\usepackage[utf8]{inputenc}\n\\usepackage{amssymb,amsmath}\n\\pagestyle{empty}\n\\setlength{\\parindent}{0in}\n\\begin{document}\n",
      latexsvg: false,
      name: "Basic-c3a2b",
      req: [[0, "any", [0]]],
      sortf: 0,
      tags: [],
      tmpls: [
        {
          afmt: "{{FrontSide}}\n\n<hr id=answer>\n\n{{Back}}",
          bafmt: "",
          bfont: "",
          bqfmt: "",
          bsize: 0,
          did: null,
          name: "Card 1",
          ord: 0,
          qfmt: "{{Front}}",
        },
      ],
      type: 0,
    },
    {
      __type__: "NoteModel",
      crowdanki_uuid: "65bac0f7-7697-11ed-8d15-b48c9d0220f8",
      css: ".card {\n font-family: arial;\n font-size: 20px;\n text-align: center;\n color: black;\n background-color: white;\n}\n",
      flds: [
        {
          description: "",
          font: "Arial",
          media: [],
          name: "Front",
          ord: 0,
          rtl: false,
          size: 20,
          sticky: false,
        },
        {
          description: "",
          font: "Arial",
          media: [],
          name: "Back",
          ord: 1,
          rtl: false,
          size: 20,
          sticky: false,
        },
      ],
      latexPost: "\\end{document}",
      latexPre:
        "\\documentclass[12pt]{article}\n\\special{papersize=3in,5in}\n\\usepackage[utf8]{inputenc}\n\\usepackage{amssymb,amsmath}\n\\pagestyle{empty}\n\\setlength{\\parindent}{0in}\n\\begin{document}\n",
      latexsvg: false,
      name: "Basic-9e74c",
      req: [[0, "any", [0]]],
      sortf: 0,
      tags: ["Causes"],
      tmpls: [
        {
          afmt: "{{FrontSide}}\n\n<hr id=answer>\n\n{{Back}}",
          bafmt: "",
          bfont: "",
          bqfmt: "",
          bsize: 0,
          did: null,
          name: "Card 1",
          ord: 0,
          qfmt: "{{Front}}",
        },
      ],
      type: 0,
      vers: [],
    },
  ],
  notes: [
    {
      __type__: "Note",
      fields: [
        '<b><span style="font-weight: 400;">Rate of reaction</span></b>',
        '<b><div><span style="font-weight: 400;">The change in concentration of a particular reactant or product per unit time.</span></div></b>',
      ],
      guid: "sI4qaaCz44",
      note_model_uuid: "65b70b2f-7697-11ed-9d99-b48c9d0220f8",
      tags: [],
    },
    {
      __type__: "Note",
      fields: [
        '<b><span style="color: rgb(34, 34, 34); font-weight: 400;">Rate equation&nbsp;</span></b>',
        '<b><span style="font-weight: 400;">A mathematical expression that relates the rate of reaction to the concentration of each reactant </span><u>raised to the appropriate power</u></b>',
      ],
      guid: "FL5$K8:@@J",
      note_model_uuid: "65b70b2f-7697-11ed-9d99-b48c9d0220f8",
      tags: [],
    },
    {
      __type__: "Note",
      fields: [
        '<b><span style="color: rgb(34, 34, 34); font-weight: 400;">Rate constant&nbsp;</span></b>',
        '<b><div><span style="font-weight: 400;">The constant of proportionality in the rate equation of the reaction</span></div></b><br>',
      ],
      guid: "s9SzuKsrNk",
      note_model_uuid: "65b70b2f-7697-11ed-9d99-b48c9d0220f8",
      tags: [],
    },
    {
      __type__: "Note",
      fields: [
        '<b><span style="color: rgb(34, 34, 34); font-weight: 400;">Order of reaction</span></b>',
        '<b><span style="font-weight: 400;">Order of reaction w.r.t. to given reactant is the power to which the concentration of that reactant is raised in the rate equation</span></b>',
      ],
      guid: "iwU[GX=2!(",
      note_model_uuid: "65b70b2f-7697-11ed-9d99-b48c9d0220f8",
      tags: [],
    },
    {
      __type__: "Note",
      fields: [
        '<b><span style="color: rgb(34, 34, 34); font-weight: 400;">Overall order of reaction</span></b>',
        '<b><span style="font-weight: 400;">Sum of the powers of the concentration terms in the rate equation</span></b>',
      ],
      guid: "ni.Y<[FQN<",
      note_model_uuid: "65b70b2f-7697-11ed-9d99-b48c9d0220f8",
      tags: [],
    },
    {
      __type__: "Note",
      fields: [
        '<b><span style="color: rgb(34, 34, 34); font-weight: 400;">Rate determining step</span></b>',
        '<b><span style="font-weight: 400;">The rate determining step is the slowest step in the </span><u>reaction mechanism of a multi-step reaction</u><span style="font-weight: 400;">. It determines the overall rate and is the step with the highest activation energy</span></b>',
      ],
      guid: "e_R6aez-*K",
      note_model_uuid: "65b70b2f-7697-11ed-9d99-b48c9d0220f8",
      tags: [],
    },
    {
      __type__: "Note",
      fields: [
        '<b><span style="color: rgb(34, 34, 34); font-weight: 400;">Half-life</span></b>',
        '<b><span style="font-weight: 400;">Time taken for the concentration of a reactant to decrease to half its initial value</span></b>',
      ],
      guid: "PzCb<3!%#4",
      note_model_uuid: "65b70b2f-7697-11ed-9d99-b48c9d0220f8",
      tags: [],
    },
    {
      __type__: "Note",
      fields: [
        '<b><span style="font-weight: 400;">Reaction mechanism</span></b>',
        '<b><span style="font-weight: 400;">A collection of elementary steps in the proper sequence showing how reactant particles are converted into products.</span></b>',
      ],
      guid: "br!Q;,>uoY",
      note_model_uuid: "65b70b2f-7697-11ed-9d99-b48c9d0220f8",
      tags: [],
    },
    {
      __type__: "Note",
      fields: [
        '<b><span style="color: rgb(34, 34, 34); font-weight: 400;">Elementary step</span></b>',
        '<b><span style="font-weight: 400;">An elementary step is a distinct step in a reaction mechanism which describes a single molecular event that involves breaking and/or making bonds</span></b>',
      ],
      guid: "gORsBNlRV{",
      note_model_uuid: "65b70b2f-7697-11ed-9d99-b48c9d0220f8",
      tags: [],
    },
    {
      __type__: "Note",
      fields: [
        '<b><span style="color: rgb(34, 34, 34); font-weight: 400;">Molecularity</span></b>',
        '<b><div><span style="font-weight: 400;">The molecularity of an elementary step in a reaction mechanism is the number of reactant particles taking part in that step</span></div><ul><li><div><span style="font-weight: 400;">Unimolecular, bimolecular, termolecular elementary step (termolecular is uncommon due to low probability of effective collisions)</span></div></li></ul></b>',
      ],
      guid: "u:H(MnSL[T",
      note_model_uuid: "65b70b2f-7697-11ed-9d99-b48c9d0220f8",
      tags: [],
    },
    {
      __type__: "Note",
      fields: [
        '<b><span style="color: rgb(34, 34, 34); font-weight: 400;">Intermediate</span></b>',
        '<b><div><span style="font-weight: 400;">An intermediate is a species that is formed in one step of a reaction mechanism and consumed in a subsequent step</span></div><ul><li><div><span style="font-weight: 400;">Not represented in the stoichiometric equation and rate equation</span></div></li></ul></b>',
      ],
      guid: "O=dD?SS&C0",
      note_model_uuid: "65b70b2f-7697-11ed-9d99-b48c9d0220f8",
      tags: [],
    },
    {
      __type__: "Note",
      fields: [
        '<b><div><span style="color: rgb(34, 34, 34); font-weight: 400;">Catalyst (Homogenous, Heterogeous, Autocatalysis)</span></div></b><br>',
        '<b><div><span style="font-weight: 400;">A substance which increases the rate of a reaction without itself undergoing any permanent chemical change</span></div><div><span style="font-weight: 400;">It increases the rate of reaction by providing an alternative reaction pathway of lower Ea than the uncatalysed reaction, resulting in a larger rate constant k</span></div><ul><li><div><span style="font-weight: 400;">Homogenous catalyst: The catalyst and the reactant are in the same phase, either liquid or gaseous</span></div></li><li><div><span style="font-weight: 400;">Heterogenous catalyst: The catalyst and the reactant are in different phases</span></div></li><li><div><span style="font-weight: 400;">Autocatalysis: A type of catalytic reaction whereby the product of the reaction acts as a catalyst for the reaction</span></div></li></ul></b>',
      ],
      guid: "u6*(e+5B0-",
      note_model_uuid: "65b70b2f-7697-11ed-9d99-b48c9d0220f8",
      tags: [],
    },
    {
      __type__: "Note",
      fields: [
        '<b><span style="color: rgb(34, 34, 34); font-weight: 400;">Poisoning of catalyst</span></b>',
        '<b><span style="font-weight: 400;">Refers to when molecules or ions chemically bond to the active sites of the catalyst, resulting in a decrease in the number of available active sites for catalysis reaction</span></b>',
      ],
      guid: "Qadv+I~NY9",
      note_model_uuid: "65b70b2f-7697-11ed-9d99-b48c9d0220f8",
      tags: [],
    },
    {
      __type__: "Note",
      fields: [
        '<b><span style="color: rgb(34, 34, 34); font-weight: 400;">Inhibitor&nbsp;</span></b>',
        '<b><div><span style="font-weight: 400;">A substance which decreases the rate of a chemical reaction</span></div></b><br>',
      ],
      guid: "iEg~_a/[To",
      note_model_uuid: "65b70b2f-7697-11ed-9d99-b48c9d0220f8",
      tags: [],
    },
    {
      __type__: "Note",
      fields: [
        '<b><span style="font-weight: 400;">Activation energy</span></b>',
        '<b><div><span style="font-weight: 400;">The minimum amount of energy that the reactant particles must possess before their collisions can result in a reaction</span></div><div><span style="font-weight: 400;">(TAKE NOTE: Ea of forward ≠ Ea of backward)</span></div></b><br>',
      ],
      guid: "e{&$7&qK4l",
      note_model_uuid: "65b70b2f-7697-11ed-9d99-b48c9d0220f8",
      tags: [],
    },
    {
      __type__: "Note",
      fields: [
        '<b><span style="font-weight: 400;">Enzymes&nbsp;</span></b>',
        '<b><span style="font-weight: 400;">Proteins which catalyse chemical reactions in living systems&nbsp;</span></b>',
      ],
      guid: "kimufu#3i_",
      note_model_uuid: "65b70b2f-7697-11ed-9d99-b48c9d0220f8",
      tags: [],
    },
    {
      __type__: "Note",
      fields: [
        '<b><span style="font-weight: 400;">Functional group</span></b>',
        '<b><span style="font-weight: 400;">A functional group is made up of an atom or group of atoms within the organic compound that is responsible for its characteristic chemical properties&nbsp;</span></b>',
      ],
      guid: "s[FC[-@g3a",
      note_model_uuid: "65b70b2f-7697-11ed-9d99-b48c9d0220f8",
      tags: [],
    },
    {
      __type__: "Note",
      fields: [
        '<b><span style="font-weight: 400;">Homologous series</span></b>',
        '<b><span style="font-weight: 400;">A homologous series is a family of compounds having the same functional group</span></b>',
      ],
      guid: "PpH]?}r3m5",
      note_model_uuid: "65b70b2f-7697-11ed-9d99-b48c9d0220f8",
      tags: [],
    },
    {
      __type__: "Note",
      fields: [
        '<b><span style="font-weight: 400;">Homologues</span></b>',
        '<b><div><span style="font-weight: 400;">Refers to the members in the same homologous series</span></div></b><br>',
      ],
      guid: "qJd4T*s=mY",
      note_model_uuid: "65b70b2f-7697-11ed-9d99-b48c9d0220f8",
      tags: [],
    },
    {
      __type__: "Note",
      fields: [
        '<b><span style="font-weight: 400;">Homolytic fission</span></b>',
        '<b><span style="font-weight: 400;">The breaking of a covalent bond such that each of the atoms involved in forming the bond acquires one of the two bonding electrons, forming free radicals</span></b>',
      ],
      guid: "B7baZwk-tT",
      note_model_uuid: "65b70b2f-7697-11ed-9d99-b48c9d0220f8",
      tags: [],
    },
    {
      __type__: "Note",
      fields: [
        '<b><span style="font-weight: 400;">Heterolytic fission</span></b>',
        '<b><span style="font-weight: 400;">The breaking of a covalent bond such that both electrons go to the same atom, typically forming positive and negative ions</span></b>',
      ],
      guid: "C^4/bgTc=;",
      note_model_uuid: "65b70b2f-7697-11ed-9d99-b48c9d0220f8",
      tags: [],
    },
    {
      __type__: "Note",
      fields: [
        '<b><span style="font-weight: 400;">Electrophile&nbsp;</span></b>',
        '<b><span style="font-weight: 400;">Electron deficient species that is able to accept a pair of electrons from an electron rich nucleophile to form a covalent bond</span></b><br>',
      ],
      guid: "lvlyi;^*1r",
      note_model_uuid: "65b70b2f-7697-11ed-9d99-b48c9d0220f8",
      tags: [],
    },
    {
      __type__: "Note",
      fields: [
        '<b><span style="font-weight: 400;">Nucleophile&nbsp;</span></b>',
        '<b><span style="font-weight: 400;">An electron-pair donor which is attracted to an electron-deficient site (itself is electron-rich)</span></b>',
      ],
      guid: "ikZj<oxUqs",
      note_model_uuid: "65b70b2f-7697-11ed-9d99-b48c9d0220f8",
      tags: [],
    },
    {
      __type__: "Note",
      fields: [
        '<b><span style="font-weight: 400;">Constitutional isomers (3 types)</span></b>',
        '<b><div><span style="font-weight: 400;">Compounds with the same molecular formula but different structural formula</span></div><ol><li><div><span style="font-weight: 400;">Chain isomers: Different arrangement of carbon atoms in the chain (Branching/Straight)</span></div></li><li><div><span style="font-weight: 400;">Positional isomers: Different position of functional group on the same carbon skeleton&nbsp;</span></div></li><li><div><span style="font-weight: 400;">Functional group isomers: Different functional group</span></div></li></ol></b>',
      ],
      guid: "ujM!ywKzNn",
      note_model_uuid: "65b70b2f-7697-11ed-9d99-b48c9d0220f8",
      tags: [],
    },
    {
      __type__: "Note",
      fields: [
        '<b><span style="font-weight: 400;">Stereoisomers (2 types)</span></b>',
        '<b><div><span style="font-weight: 400;">Compounds with the same molecular formula and structural formula but differ in the way in which their atoms are arranged in space relative to one another&nbsp;</span></div><div><span style="font-weight: 400;"><br></span></div><div><span style="font-weight: 400;">Cis-trans isomerism:&nbsp;</span></div><ul><li><div><span style="font-weight: 400;">(1) Restricted rotation about a bond due to presence of double bond or ring structure (*C=C bond in ring structure does not exhibit cis-trans!)</span></div></li><li><div><span style="font-weight: 400;">(2) For alkene, each C atom in C=C bond must have two different groups attached to it and for cyclic compound, two or more of the C atoms in the ring must each have two different groups attached to them</span></div></li></ul><div><span style="font-weight: 400;">Enantiomerism:&nbsp;</span><span style="font-weight: 400;">A compound displays enantiomerism if it contains a chiral carbon and forms a non-superimposable mirror image&nbsp;</span></div></b><ul>\n<li>Criteria: Molecule\'s mirror image is non-superimposable and no plane of symmetry</li>\n</ul>\n<div>(SPECIAL CASE: extended chiral centre, 2 adjacent C=C bonds e.g. CH<sub>3</sub>CH=C=CHCH<sub>3</sub>)</div><b><br></b>',
      ],
      guid: "zi9F*F*I8#",
      note_model_uuid: "65b70b2f-7697-11ed-9d99-b48c9d0220f8",
      tags: [],
    },
    {
      __type__: "Note",
      fields: [
        '<b><span style="font-weight: 400;">Chiral compound</span></b>',
        '<b><span style="font-weight: 400;">Compounds that do not have a plane of symmetry and usually contain one or more chiral centres</span></b>',
      ],
      guid: "Bj3>g6B#}I",
      note_model_uuid: "65b70b2f-7697-11ed-9d99-b48c9d0220f8",
      tags: [],
    },
    {
      __type__: "Note",
      fields: [
        '<b><span style="font-weight: 400;">Meso compound</span></b>',
        '<b><span style="font-weight: 400;">Compounds that contain more than one chiral centers but has a plane of symmetry. It has mirror images that are superimposable and is optically inactive.&nbsp;</span></b>',
      ],
      guid: "jx,[pt9|ck",
      note_model_uuid: "65b70b2f-7697-11ed-9d99-b48c9d0220f8",
      tags: [],
    },
    {
      __type__: "Note",
      fields: [
        '<b><div><span style="font-weight: 400;">Optical activity&nbsp;</span></div></b><br>',
        '<b><div><b><span style="font-weight: 400;">The ability of a compound to rotate</span><span style="font-weight: 400;">&nbsp;plane-polarized light in either a clockwise or anti-clockwise direction</span></b><span style="font-weight: 400;"><br></span></div><div><span style="font-weight: 400;">- Measure optical activity of a pure sample of ____ with a polarimeter</span></div><br></b>',
      ],
      guid: "ol$D1*iebJ",
      note_model_uuid: "65b70b2f-7697-11ed-9d99-b48c9d0220f8",
      tags: [],
    },
    {
      __type__: "Note",
      fields: [
        '<b><span style="font-weight: 400;">Halogenation</span></b>',
        '<b><span style="font-weight: 400;">The substitution of one or more H atoms of the alkane by a halogen atom</span></b>',
      ],
      guid: "HDGk`,FQXW",
      note_model_uuid: "65b70b2f-7697-11ed-9d99-b48c9d0220f8",
      tags: [],
    },
    {
      __type__: "Note",
      fields: [
        '<b><div><span style="font-weight: 400;">Free radical</span></div></b>',
        '<b><span style="font-weight: 400;">A species with an </span><u>unpaired</u><span style="font-weight: 400;"> electron</span></b>',
      ],
      guid: "l>6K??FMcD",
      note_model_uuid: "65b70b2f-7697-11ed-9d99-b48c9d0220f8",
      tags: [],
    },
    {
      __type__: "Note",
      fields: [
        '<b><div><span style="font-weight: 400;">Natural gas</span></div></b>',
        '<b><span style="font-weight: 400;">Contains mainly methane with a small amount of the other gaseous alkanes such as ethane, propane and butane&nbsp;</span></b>',
      ],
      guid: "P;okTz-{3O",
      note_model_uuid: "65b70b2f-7697-11ed-9d99-b48c9d0220f8",
      tags: [],
    },
    {
      __type__: "Note",
      fields: [
        '<b><span style="font-weight: 400;">Crude oil/Petroleum</span></b>',
        '<b><span style="font-weight: 400;">Complex mixture of hydrocarbons consisting of alkanes, cycloalkanes and aromatic compounds&nbsp;</span></b>',
      ],
      guid: "N>ln`d&!I[",
      note_model_uuid: "65b70b2f-7697-11ed-9d99-b48c9d0220f8",
      tags: [],
    },
    {
      __type__: "Note",
      fields: [
        '<b><div><span style="font-weight: 400;">Alkenes</span></div></b>',
        '<b><div><span style="font-weight: 400;">Alkenes are hydrocarbons that contain one or more carbon-carbon double bonds (C=C). The functional group of an alkenes is the C=C bond</span></div></b>',
      ],
      guid: "z]A,WaWsYz",
      note_model_uuid: "65b70b2f-7697-11ed-9d99-b48c9d0220f8",
      tags: [],
    },
    {
      __type__: "Note",
      fields: [
        '<b><div><span style="font-weight: 400;">Carbocation</span></div></b>',
        '<b><span style="font-weight: 400;">An ion with a positively charged carbon&nbsp;</span></b>',
      ],
      guid: "twBgiyA?H6",
      note_model_uuid: "65b70b2f-7697-11ed-9d99-b48c9d0220f8",
      tags: [],
    },
    {
      __type__: "Note",
      fields: [
        "Ionic bond",
        "The electrostatic attraction between anions and cations&nbsp;",
      ],
      guid: "jESRQQ?m(O",
      note_model_uuid: "65b70b2f-7697-11ed-9d99-b48c9d0220f8",
      tags: [],
    },
    {
      __type__: "Note",
      fields: [
        "Covalent bonds",
        "Electrostatic attraction between the shared pair of electrons and the positively charged<b> nuclei&nbsp;</b>",
      ],
      guid: "nRVFcfrfca",
      note_model_uuid: "65b70b2f-7697-11ed-9d99-b48c9d0220f8",
      tags: [],
    },
    {
      __type__: "Note",
      fields: [
        "Metallic bonds",
        "The electrostatic attraction between positively charged metal ions and the sea of delocalised electrons",
      ],
      guid: "BjJ<+6b:A2",
      note_model_uuid: "65b70b2f-7697-11ed-9d99-b48c9d0220f8",
      tags: [],
    },
    {
      __type__: "Note",
      fields: [
        "Dative covalent bond",
        "A covalent bond where the shared pair of electrons is provided by only one of the bonding atoms",
      ],
      guid: "DNPvG>Js]9",
      note_model_uuid: "65b70b2f-7697-11ed-9d99-b48c9d0220f8",
      tags: [],
    },
    {
      __type__: "Note",
      fields: [
        '<b><span style="font-weight: 400;">Strong acid</span></b>',
        '<b><span style="font-weight: 400;">A strong acid is one which undergoes complete dissociation in aqueous solution to produce H</span><span style="font-weight: 400;">+</span><span style="font-weight: 400;"> (aq)&nbsp;</span></b><div><b>[E.g. HCl, HNO<sub>3</sub>]</b></div>',
      ],
      guid: "M?0ccZ3Ubd",
      note_model_uuid: "65b70b2f-7697-11ed-9d99-b48c9d0220f8",
      tags: [],
    },
    {
      __type__: "Note",
      fields: [
        '<b><span style="font-weight: 400;">Weak acid</span></b>',
        '<b><span style="font-weight: 400;">A weak acid is one which undergoes partial dissociation in aqueous solution to produce H</span><span style="font-weight: 400;"><sup>+</sup></span><span style="font-weight: 400;"> (aq)&nbsp;</span></b><div><b>[E.g. Ethanoic acid CH<sub>3</sub>COOH, Hydrogen cyanide HCN]</b></div>',
      ],
      guid: "HKL{f;heh^",
      note_model_uuid: "65b70b2f-7697-11ed-9d99-b48c9d0220f8",
      tags: [],
    },
    {
      __type__: "Note",
      fields: [
        '<b><span style="font-weight: 400;">Concentration of acid</span></b>',
        '<b><span style="font-weight: 400;">The amount of acid per unit volume of the solution</span></b>',
      ],
      guid: "OC5QqIhz/?",
      note_model_uuid: "65b70b2f-7697-11ed-9d99-b48c9d0220f8",
      tags: [],
    },
    {
      __type__: "Note",
      fields: [
        '<b><span style="font-weight: 400;">Strong base</span></b>',
        '<b><span style="font-weight: 400;">A strong base is one which undergoes complete dissociation in aqueous solution to produce OH</span><span style="font-weight: 400;"><sup>-</sup></span><span style="font-weight: 400;"> (aq)&nbsp;</span></b><div><b>[E.g. NaOH, KOH, Ba(OH)<sup>2</sup>]</b></div>',
      ],
      guid: "I5zaO&THk@",
      note_model_uuid: "65b70b2f-7697-11ed-9d99-b48c9d0220f8",
      tags: [],
    },
    {
      __type__: "Note",
      fields: [
        '<b><div><span style="font-weight: 400;">Weak base</span></div></b>',
        '<b><span style="font-weight: 400;">A weak base is one which undergoes partial ionisation in aqueous solution to produce OH</span><span style="font-weight: 400;"><sup>-</sup></span><span style="font-weight: 400;"><sup> </sup>(aq)&nbsp;</span></b><div><b>[E.g. NH<sub>3</sub>, Na<sub>2</sub>CO<sub>3</sub>, CH<sub>3</sub>CH<sub>2</sub>NH<sub>2</sub>]</b></div>',
      ],
      guid: "yz^Rt<t)8T",
      note_model_uuid: "65b70b2f-7697-11ed-9d99-b48c9d0220f8",
      tags: [],
    },
    {
      __type__: "Note",
      fields: [
        '<b><div><span style="font-weight: 400;">Bronsted-Lowry Acid</span></div></b>',
        '<b><span style="font-weight: 400;">A proton donor</span></b>',
      ],
      guid: "tNSbfL4ISw",
      note_model_uuid: "65b70b2f-7697-11ed-9d99-b48c9d0220f8",
      tags: [],
    },
    {
      __type__: "Note",
      fields: [
        '<b><span style="font-weight: 400;">Bronsted-Lowry Base</span></b>',
        '<b><span style="font-weight: 400;">A proton acceptor</span></b>',
      ],
      guid: "fFk~>^{r=R",
      note_model_uuid: "65b70b2f-7697-11ed-9d99-b48c9d0220f8",
      tags: [],
    },
    {
      __type__: "Note",
      fields: [
        '<b><div><span style="font-weight: 400;">Lewis Acid</span></div></b>',
        '<b><span style="font-weight: 400;">Any species that can accept a pair of electrons (from a Lewis base) to form a dative covalent bond</span></b>',
      ],
      guid: "K(D0?UN}.X",
      note_model_uuid: "65b70b2f-7697-11ed-9d99-b48c9d0220f8",
      tags: [],
    },
    {
      __type__: "Note",
      fields: [
        '<b><span style="font-weight: 400;">Lewis Base</span></b>',
        '<b><span style="font-weight: 400;">Any species that can donate a pair of electrons (to a Lewis acid) to form a dative covalent bond&nbsp;</span></b>',
      ],
      guid: "OcXRo,`T^U",
      note_model_uuid: "65b70b2f-7697-11ed-9d99-b48c9d0220f8",
      tags: [],
    },
    {
      __type__: "Note",
      fields: [
        '<b><span style="font-weight: 400;">Acid dissociation constant</span></b>',
        '<b><span style="font-weight: 400;">The acid dissociation constant, Ka, is an equilibrium constant which measures the extent to which an acid is dissociated, </span><span style="font-weight: 400; font-style: italic;">i.e. </span><span style="font-weight: 400;">measures the strength of the acid</span></b>',
      ],
      guid: "Cj=F5xlwyA",
      note_model_uuid: "65b70b2f-7697-11ed-9d99-b48c9d0220f8",
      tags: [],
    },
    {
      __type__: "Note",
      fields: [
        '<b><span style="font-weight: 400;">Buffer solution&nbsp;</span></b>',
        '<b><span style="font-weight: 400;">A solution which is able to resist pH changes when a small amount of acid or base is added</span></b>',
      ],
      guid: "L0EXk;o.JF",
      note_model_uuid: "65b70b2f-7697-11ed-9d99-b48c9d0220f8",
      tags: [],
    },
    {
      __type__: "Note",
      fields: [
        '<b><span style="font-weight: 400;">Buffer capacity</span></b>',
        '<b><span style="font-weight: 400;">A measure of the ability of a buffer to resist pH change</span></b>',
      ],
      guid: "xqQ?3+X]YL",
      note_model_uuid: "65b70b2f-7697-11ed-9d99-b48c9d0220f8",
      tags: [],
    },
    {
      __type__: "Note",
      fields: [
        '<b><span style="font-weight: 400;">Equivalence point</span></b>',
        '<b><span style="font-weight: 400;">The point when the amount of acid needed to react with the amount of base is precisely that required by the stoichiometric equation</span></b>',
      ],
      guid: "n#lNTCt5Dk",
      note_model_uuid: "65b70b2f-7697-11ed-9d99-b48c9d0220f8",
      tags: [],
    },
    {
      __type__: "Note",
      fields: [
        '<b><div><span style="font-weight: 400;">End-point</span></div></b>',
        '<b><span style="font-weight: 400;">The point during a titration at which a distinct colour change&nbsp;</span></b><b><span style="font-weight: 400;">occurs,</span></b><b><span style="font-weight: 400;">&nbsp;brought about by the use of a suitable indicator&nbsp;</span></b>',
      ],
      guid: "5t^[=m6+e",
      note_model_uuid: "65b70b2f-7697-11ed-9d99-b48c9d0220f8",
      tags: [],
    },
    {
      __type__: "Note",
      fields: [
        '<b><span style="font-weight: 400;">Suitable indicator</span></b>',
        '<b><span style="font-weight: 400;">A suitable indicator is one where its pH range coincides with the region of rapid pH change in the titration curve</span></b>',
      ],
      guid: "xKE$j$t=3M",
      note_model_uuid: "65b70b2f-7697-11ed-9d99-b48c9d0220f8",
      tags: [],
    },
    {
      __type__: "Note",
      fields: [
        "Effective buffer range",
        "The pH range over which the buffer acts effectively in keeping pH approximately constant.",
      ],
      guid: "w%6d=JktCZ",
      note_model_uuid: "65b70b2f-7697-11ed-9d99-b48c9d0220f8",
      tags: [],
    },
    {
      __type__: "Note",
      fields: [
        "<b>Standard enthalpy change of reaction</b>",
        '<b><span style="font-weight: 400;">The energy change in a chemical reaction when the molar quantities of the reactants stated in the chemical equation react under standard conditions of 1 bar and 298K</span></b>',
      ],
      guid: "v9w5H~K+98",
      note_model_uuid: "65b70b2f-7697-11ed-9d99-b48c9d0220f8",
      tags: [],
    },
    {
      __type__: "Note",
      fields: [
        "<b>Standard enthalpy change of formation of substance</b>",
        '<b><span style="font-weight: 400;">The energy change when</span><span style="color: rgb(255, 0, 0);"> 1 mole of pure substances in a <u>specified state</u></span><span style="font-weight: 400;"> is formed from its</span><span style="color: rgb(255, 0, 0);"> constituent elements in their standard states</span><span style="font-weight: 400;"> under standard conditions of 1 bar and 298K</span></b>',
      ],
      guid: "cxFQZGK}G/",
      note_model_uuid: "65b70b2f-7697-11ed-9d99-b48c9d0220f8",
      tags: [],
    },
    {
      __type__: "Note",
      fields: [
        "<b>Standard enthalpy change of formation of element</b>",
        "Enthalpy change of formation of element is zero&nbsp;",
      ],
      guid: "xUP;64r~C<",
      note_model_uuid: "65b70b2f-7697-11ed-9d99-b48c9d0220f8",
      tags: [],
    },
    {
      __type__: "Note",
      fields: [
        "<b>Standard enthalpy change of combustion</b>",
        '<b><span style="font-weight: 400;">The energy released when </span><span style="color: rgb(255, 0, 0);">1 mole of the substance</span><span style="font-weight: 400;"> is completely burnt in excess oxygen under standard conditions of 1 bar and 298K</span></b>',
      ],
      guid: "l}wTh^ZKEz",
      note_model_uuid: "65b70b2f-7697-11ed-9d99-b48c9d0220f8",
      tags: [],
    },
    {
      __type__: "Note",
      fields: [
        "<b>Standard enthalpy change of neutralisation</b>",
        '<b><span style="font-weight: 400;">The energy change when the </span><span style="color: rgb(255, 0, 0);">acid and the base</span><span style="font-weight: 400;"> react to form </span><span style="color: rgb(255, 0, 0);">1 mole of water</span><span style="font-weight: 400;"> under standard conditions 1 bar and 298K</span></b>',
      ],
      guid: "kRpEg+9u/r",
      note_model_uuid: "65b70b2f-7697-11ed-9d99-b48c9d0220f8",
      tags: [],
    },
    {
      __type__: "Note",
      fields: [
        '<b><span style="color: rgb(34, 34, 34);">Standard enthalpy change of atomisation of an element</span></b>',
        '<b><span style="font-weight: 400;">The energy absorbed when </span><span style="color: rgb(255, 0, 0);">1 mole of gaseous atoms </span><span style="font-weight: 400;">is formed from the element under standard conditions of 1 bar and 298K</span></b>',
      ],
      guid: "xy|HX*^._/",
      note_model_uuid: "65b70b2f-7697-11ed-9d99-b48c9d0220f8",
      tags: [],
    },
    {
      __type__: "Note",
      fields: [
        '<b><span style="color: rgb(34, 34, 34);">Standard enthalpy change of atomisation of a compound</span></b>',
        '<b><span style="font-weight: 400;">The energy absorbed when </span><span style="color: rgb(255, 0, 0);">1 mole of compound</span><span style="font-weight: 400;"> is converted to gaseous atoms under standard conditions of 1 bar and 298K</span></b>',
      ],
      guid: "LdR6@fxOus",
      note_model_uuid: "65b70b2f-7697-11ed-9d99-b48c9d0220f8",
      tags: [],
    },
    {
      __type__: "Note",
      fields: [
        '<b><span style="color: rgb(34, 34, 34);">Bond Dissociation Energy&nbsp;</span></b>',
        '<b><span style="font-weight: 400;">The energy required to break </span><span style="color: rgb(255, 0, 0);">1 mole of that particular X-Y</span><span style="font-weight: 400;"> bond in a particular compound in gaseous state&nbsp;</span></b>',
      ],
      guid: "q(lx#P#7-I",
      note_model_uuid: "65b70b2f-7697-11ed-9d99-b48c9d0220f8",
      tags: [],
    },
    {
      __type__: "Note",
      fields: [
        '<b><span style="color: rgb(34, 34, 34);">Bond Energy&nbsp;</span></b>',
        '<b><span style="font-weight: 400;">The average energy required to break </span><span style="color: rgb(255, 0, 0);">1 mole of the X-Y bond</span><span style="font-weight: 400;"> in gaseous state</span></b>',
      ],
      guid: "vzB=%RE)Gp",
      note_model_uuid: "65b70b2f-7697-11ed-9d99-b48c9d0220f8",
      tags: [],
    },
    {
      __type__: "Note",
      fields: [
        '<b><div><span style="color: rgb(34, 34, 34);">Ionisation Energy&nbsp;</span></div></b>',
        '<b><div>1st IE: <span style="font-weight: 400;">The energy required to remove 1 mole of electrons from 1 mole of gaseous atoms to form 1 mole of singly positively charged gaseous ions</span></div><br>2nd IE: <span style="font-weight: 400;">The energy required to remove 1 mole of electrons from 1 mole of singly positively charged gaseous ions to form 1 mole of doubly positively charged gaseous ions</span></b>',
      ],
      guid: "kh(AJ?RSmq",
      note_model_uuid: "65b70b2f-7697-11ed-9d99-b48c9d0220f8",
      tags: [],
    },
    {
      __type__: "Note",
      fields: [
        '<b><span style="color: rgb(34, 34, 34);">Electron affinity</span></b>',
        '<b><div>1st EA: <span style="font-weight: 400;">The energy change when 1 mole of gaseous atoms acquires 1 mole of electrons to form 1 mole of singly negatively charged gaseous ions</span></div>2nd EA: <span style="font-weight: 400;">The energy absorbed when 1 mole of singly negatively charged gaseous ions acquires 1 mole of electrons to form 1 mole of doubly negatively charged gaseous ions</span></b>',
      ],
      guid: "t1rEg??:NM",
      note_model_uuid: "65b70b2f-7697-11ed-9d99-b48c9d0220f8",
      tags: [],
    },
    {
      __type__: "Note",
      fields: [
        '<b><span style="color: rgb(34, 34, 34);">Lattice Energy&nbsp;</span></b>',
        '<b><span style="font-weight: 400;">The energy released when </span><span style="color: rgb(255, 0, 0);">1 mole of the solid ionic compound</span><span style="font-weight: 400;"> is formed from its constituent gaseous ions under standard conditions of 1 bar and 298K</span></b>',
      ],
      guid: "sDY}o:H^T`",
      note_model_uuid: "65b70b2f-7697-11ed-9d99-b48c9d0220f8",
      tags: [],
    },
    {
      __type__: "Note",
      fields: [
        '<b><span style="color: rgb(34, 34, 34);">Standard enthalpy change of hydration</span></b>',
        '<b><span style="font-weight: 400;">The energy released when </span><span style="color: rgb(255, 0, 0);">1 mole of gaseous ion</span><span style="font-weight: 400;"> is hydrated under standard conditions of 1 bar and 298K</span></b>',
      ],
      guid: "N)j|)e%Fp^",
      note_model_uuid: "65b70b2f-7697-11ed-9d99-b48c9d0220f8",
      tags: [],
    },
    {
      __type__: "Note",
      fields: [
        '<b><span style="color: rgb(34, 34, 34);">Standard enthalpy change of solution</span></b>',
        '<b><span style="font-weight: 400;">The energy change when </span><span style="color: rgb(255, 0, 0);">1 mole of substance</span><span style="font-weight: 400;"> is completely dissolved in a solvent/water </span><u>to form an infinitely dilute solution</u><span style="font-weight: 400;"> under standard conditions of 1 bar and 298K</span></b>',
      ],
      guid: "ssk!Qrv;8&",
      note_model_uuid: "65b70b2f-7697-11ed-9d99-b48c9d0220f8",
      tags: [],
    },
    {
      __type__: "Note",
      fields: [
        '<b><span style="font-weight: 400;">Enthalpy</span></b>',
        '<b><span style="font-weight: 400;">A measure of the energy content of the system&nbsp;</span></b>',
      ],
      guid: "IvRGjwq,{0",
      note_model_uuid: "65b70b2f-7697-11ed-9d99-b48c9d0220f8",
      tags: [],
    },
    {
      __type__: "Note",
      fields: [
        '<b><span style="font-weight: 400;">Enthalpy change</span></b>',
        '<b><div><span style="font-weight: 400;">The change in energy content of a process in a system at </span><u>constant pressure </u><span style="font-weight: 400;">OR</span></div><div><span style="font-weight: 400;">The difference between the quantity of heat absorbed to break the bonds in the reactants and that released during the formation of new bonds in the products at constant pressure (Bond breaking - bond forming)</span></div></b>',
      ],
      guid: "qc]^M8Y#[O",
      note_model_uuid: "65b70b2f-7697-11ed-9d99-b48c9d0220f8",
      tags: [],
    },
    {
      __type__: "Note",
      fields: [
        '<b><span style="font-weight: 400;">Exothermic reaction</span></b>',
        '<b><span style="font-weight: 400;">A reaction in which energy is released to the surroundings</span></b>',
      ],
      guid: "e.FHxhu01|",
      note_model_uuid: "65b70b2f-7697-11ed-9d99-b48c9d0220f8",
      tags: [],
    },
    {
      __type__: "Note",
      fields: [
        '<b><span style="font-weight: 400;">Endothermic reaction</span></b>',
        '<b><span style="font-weight: 400;">A reaction in which energy is absorbed from the surroundings&nbsp;</span></b>',
      ],
      guid: "u1b@uUOgSy",
      note_model_uuid: "65b70b2f-7697-11ed-9d99-b48c9d0220f8",
      tags: [],
    },
    {
      __type__: "Note",
      fields: [
        '<b><span style="font-weight: 400;">Standard Conditions</span></b>',
        '<b><span style="font-weight: 400;">Pressure: 1 bar (10^</span><span style="font-weight: 400;">5</span><span style="font-weight: 400;"> Pa) + Temperature: 298K (25 degrees celsius</span><span style="font-weight: 400;">) + All substances involved are in their standard states</span></b>',
      ],
      guid: "EJh*OJSn3%",
      note_model_uuid: "65b70b2f-7697-11ed-9d99-b48c9d0220f8",
      tags: [],
    },
    {
      __type__: "Note",
      fields: [
        '<b><span style="font-weight: 400;">Specific heat capacity</span></b>',
        '<b><span style="font-weight: 400;">The quantity of heat required to raise the temperature of a unit mass of a substance by 1K/degree celsius</span></b>',
      ],
      guid: "c{E/n/st&|",
      note_model_uuid: "65b70b2f-7697-11ed-9d99-b48c9d0220f8",
      tags: [],
    },
    {
      __type__: "Note",
      fields: [
        '<b><span style="font-weight: 400;">Heat capacity</span></b>',
        '<b><span style="font-weight: 400;">The quantity of heat required to raise the temperature of a substance by 1K/1 degree celsius&nbsp;</span></b>',
      ],
      guid: "HV`QC[>Ol}",
      note_model_uuid: "65b70b2f-7697-11ed-9d99-b48c9d0220f8",
      tags: [],
    },
    {
      __type__: "Note",
      fields: [
        '<b><span style="font-weight: 400;">Hess’ Law</span></b>',
        '<b><span style="font-weight: 400;">Hess’ Law states that the enthalpy change of a chemical reaction is determined by the initial and final states of the system and is independent of the pathways taken</span></b>',
      ],
      guid: "HfC~$J*qh%",
      note_model_uuid: "65b70b2f-7697-11ed-9d99-b48c9d0220f8",
      tags: [],
    },
    {
      __type__: "Note",
      fields: [
        '<b><span style="font-weight: 400;">Experimental LE</span></b>',
        '<b><span style="font-weight: 400;">Obtained using the experimental way, using experimentally obtained enthalpy changes in a Born-Haber cycle</span></b>',
      ],
      guid: "p^K#:|i<v)",
      note_model_uuid: "65b70b2f-7697-11ed-9d99-b48c9d0220f8",
      tags: [],
    },
    {
      __type__: "Note",
      fields: [
        '<b><span style="font-weight: 400;">Theoretical LE</span></b>',
        '<b><span style="font-weight: 400;">Obtained the theoretical way, doing calculations using an equation based on a purely ionic model</span></b>',
      ],
      guid: "EeF|>-_nDy",
      note_model_uuid: "65b70b2f-7697-11ed-9d99-b48c9d0220f8",
      tags: [],
    },
    {
      __type__: "Note",
      fields: [
        '<b><span style="font-weight: 400;">Spontaneous process</span></b>',
        '<b><span style="font-weight: 400;">A spontaneous process is one that, once started, will continue without any external assistance</span></b>',
      ],
      guid: "cv:OHu%UGa",
      note_model_uuid: "65b70b2f-7697-11ed-9d99-b48c9d0220f8",
      tags: [],
    },
    {
      __type__: "Note",
      fields: [
        '<b><span style="font-weight: 400;">Non-spontaneous process</span></b>',
        '<b><span style="font-weight: 400;">A non-spontaneous process will not occur unless some external assistance is </span><u>continuously</u><span style="font-weight: 400;"> supplied</span></b>',
      ],
      guid: "t8cCzQr($-",
      note_model_uuid: "65b70b2f-7697-11ed-9d99-b48c9d0220f8",
      tags: [],
    },
    {
      __type__: "Note",
      fields: [
        '<b><span style="font-weight: 400;">Entropy</span></b>',
        '<b>A measure of the disorder of matter and energy in the system. <span style="font-weight: 400;">The more ways matter in the system can be arranged, and the more ways energy in the system can be dispersed, the more disordered the system is and the larger is its entropy</span></b>',
      ],
      guid: "Ey[*|EG|P]",
      note_model_uuid: "65b70b2f-7697-11ed-9d99-b48c9d0220f8",
      tags: [],
    },
    {
      __type__: "Note",
      fields: [
        '<b><span style="font-weight: 400;">Entropy change</span></b>',
        '<b><span style="font-weight: 400;">A measure of change in disorder of the system</span></b>',
      ],
      guid: "I0n>uVE3w)",
      note_model_uuid: "65b70b2f-7697-11ed-9d99-b48c9d0220f8",
      tags: [],
    },
    {
      __type__: "Note",
      fields: [
        '<b><span style="font-weight: 400;">Standard Electrode Potential</span></b>',
        '<b><span style="font-weight: 400;">The standard electrode potential of a half-cell is the electromotive force, measured at 298 K, between the half-cell and the standard hydrogen electrode, in which the concentration of any reacting species in aqueous solution is 1 mol dm</span><span style="font-weight: 400;">-3</span><span style="font-weight: 400;"> and any gaseous species is at a pressure of 1 bar.&nbsp;</span></b>',
      ],
      guid: "v@P^odch5S",
      note_model_uuid: "65b70b2f-7697-11ed-9d99-b48c9d0220f8",
      tags: [],
    },
    {
      __type__: "Note",
      fields: [
        '<b><span style="font-weight: 400;">Solubility</span></b>',
        '<b><span style="font-weight: 400;">The solubility of a solute in a solvent the maximum amount of solute which can dissolve in a given amount of solvent </span><u>at a particular temperature&nbsp;</u></b>',
      ],
      guid: "bdA@u7mdtK",
      note_model_uuid: "65b70b2f-7697-11ed-9d99-b48c9d0220f8",
      tags: [],
    },
    {
      __type__: "Note",
      fields: [
        '<b><span style="font-weight: 400;">Saturated solution</span></b>',
        '<b><span style="font-weight: 400;">A solution containing the maximum amount of solute that can be dissolved in the given amount of solvent.&nbsp;</span></b>',
      ],
      guid: "GB+TSd9YDJ",
      note_model_uuid: "65b70b2f-7697-11ed-9d99-b48c9d0220f8",
      tags: [],
    },
    {
      __type__: "Note",
      fields: [
        '<b><span style="font-weight: 400;">Solubility product</span></b>',
        '<b><span style="font-weight: 400;">The solubility product of a sparingly soluble salt is the equilibrium constant for the equilibrium established between the undissolved salt and its constituent ions in a saturated solution</span></b>',
      ],
      guid: "g79zlh?=[,",
      note_model_uuid: "65b70b2f-7697-11ed-9d99-b48c9d0220f8",
      tags: [],
    },
    {
      __type__: "Note",
      fields: [
        '<b><span style="font-weight: 400;">Ionic product</span></b>',
        '<b><span style="font-weight: 400;">The ionic product is the product of the concentration of the constituent ions in a solution at that instant raised to the stoichiometric coefficients of the ions</span></b>',
      ],
      guid: "G,$oBQ_6Yn",
      note_model_uuid: "65b70b2f-7697-11ed-9d99-b48c9d0220f8",
      tags: [],
    },
    {
      __type__: "Note",
      fields: [
        '<b><span style="font-weight: 400;">Common ion effect</span></b>',
        '<b><span style="font-weight: 400;">Refers to the reduced solubility of a salt in a solution that already contains an ion common to that salt.&nbsp;</span></b>',
      ],
      guid: "w].kq>?w9{",
      note_model_uuid: "65b70b2f-7697-11ed-9d99-b48c9d0220f8",
      tags: [],
    },
    {
      __type__: "Note",
      fields: [
        '<b><span style="font-weight: 400;">Proton number</span></b>',
        '<b><span style="font-weight: 400;">The number of protons in the nucleus of an atom of an element</span></b>',
      ],
      guid: "caQkKs.FyQ",
      note_model_uuid: "65b70b2f-7697-11ed-9d99-b48c9d0220f8",
      tags: [],
    },
    {
      __type__: "Note",
      fields: [
        '<b><span style="font-weight: 400;">Nucleon number</span></b>',
        '<b><span style="font-weight: 400;">The total number of protons and neutrons in the nucleus of an atom of an element</span></b>',
      ],
      guid: "ym}>)XvH+{",
      note_model_uuid: "65b70b2f-7697-11ed-9d99-b48c9d0220f8",
      tags: [],
    },
    {
      __type__: "Note",
      fields: [
        '<b><span style="font-weight: 400;">Isotope</span></b>',
        '<b><span style="font-weight: 400;">Isotopes of an element are atoms with the same number of protons but different number of neutrons in the nucleus</span></b>',
      ],
      guid: "Gxr(efGq%4",
      note_model_uuid: "65b70b2f-7697-11ed-9d99-b48c9d0220f8",
      tags: [],
    },
    {
      __type__: "Note",
      fields: [
        '<b><span style="font-weight: 400;">Relative atomic mass&nbsp;</span></b>',
        '<b><span style="color: rgb(34, 34, 34); font-weight: 400;">The ratio of the </span><span style="color: rgb(34, 34, 34);"><u>average</u></span><span style="color: rgb(34, 34, 34); font-weight: 400;"> mass of one atom of an element to one twelfth of the mass of an atom of carbon-12</span></b>',
      ],
      guid: "C:hdi`to4<",
      note_model_uuid: "65b70b2f-7697-11ed-9d99-b48c9d0220f8",
      tags: [],
    },
    {
      __type__: "Note",
      fields: [
        '<b><span style="font-weight: 400;">Relative isotopic mass&nbsp;</span></b>',
        '<b><span style="color: rgb(34, 34, 34); font-weight: 400;">The ratio of the mass of one atom of the isotope to one twelfth of the mass of an atom of carbon-12</span></b>',
      ],
      guid: "tf@4R%}Y?k",
      note_model_uuid: "65b70b2f-7697-11ed-9d99-b48c9d0220f8",
      tags: [],
    },
    {
      __type__: "Note",
      fields: [
        '<b><span style="font-weight: 400;">Relative molecular mass</span></b>',
        '<b><div><span style="color: rgb(34, 34, 34); font-weight: 400;">The ratio of the average mass of one molecule of the substance to one twelfth of the mass of an atom of carbon-12</span></div></b><br>',
      ],
      guid: "qJL:TK?(<M",
      note_model_uuid: "65b70b2f-7697-11ed-9d99-b48c9d0220f8",
      tags: [],
    },
    {
      __type__: "Note",
      fields: [
        '<b><span style="font-weight: 400;">Relative formula mass</span></b>',
        '<b><span style="color: rgb(34, 34, 34); font-weight: 400;">The ratio of the </span><span style="color: rgb(34, 34, 34);"><u>average</u></span><span style="color: rgb(34, 34, 34); font-weight: 400;"> mass of one formula unit of a substance to one twelfth of the mass of an atom of carbon-12.</span></b>',
      ],
      guid: "N<=K2:(e;&",
      note_model_uuid: "65b70b2f-7697-11ed-9d99-b48c9d0220f8",
      tags: [],
    },
    {
      __type__: "Note",
      fields: [
        '<b><span style="font-weight: 400;">Mole</span></b>',
        '<b><span style="color: rgb(34, 34, 34); font-weight: 400;">A mole of a substance is the amount of that substance which contains 6.02 x 10^</span><span style="color: rgb(34, 34, 34); font-weight: 400;">23</span><span style="color: rgb(34, 34, 34); font-weight: 400;"> elementary entities of that substance</span></b>',
      ],
      guid: "EWm*V1PB;i",
      note_model_uuid: "65b70b2f-7697-11ed-9d99-b48c9d0220f8",
      tags: [],
    },
    {
      __type__: "Note",
      fields: [
        '<b><span style="font-weight: 400;">Empirical formula&nbsp;</span></b>',
        '<b><span style="color: rgb(34, 34, 34); font-weight: 400;">The formula that shows the simplest whole number ratio of the atoms of different elements present in one molecule of the compound</span></b>',
      ],
      guid: "KOy`kDpQX?",
      note_model_uuid: "65b70b2f-7697-11ed-9d99-b48c9d0220f8",
      tags: [],
    },
    {
      __type__: "Note",
      fields: [
        '<b><span style="font-weight: 400;">Molecular formula</span></b>',
        '<b><span style="color: rgb(34, 34, 34); font-weight: 400;">The formula that shows the actual number of atoms of each element present in one molecule of the compound&nbsp;</span></b>',
      ],
      guid: "BY~/#:oGv0",
      note_model_uuid: "65b70b2f-7697-11ed-9d99-b48c9d0220f8",
      tags: [],
    },
    {
      __type__: "Note",
      fields: [
        '<b><span style="font-weight: 400;">Disproportionation</span></b>',
        '<b><span style="color: rgb(34, 34, 34); font-weight: 400;">A redox reaction in which the same element in a substance is simultaneously oxidised and reduced&nbsp;</span></b>',
      ],
      guid: "t/QO/xE~a#",
      note_model_uuid: "65b70b2f-7697-11ed-9d99-b48c9d0220f8",
      tags: [],
    },
    {
      __type__: "Note",
      fields: [
        '<b><span style="font-weight: 400;">Isoelectronic</span></b>',
        '<b><span style="font-weight: 400;">Species with the same total number of electrons</span></b>',
      ],
      guid: "p8G>(?cNVF",
      note_model_uuid: "65b70b2f-7697-11ed-9d99-b48c9d0220f8",
      tags: [],
    },
    {
      __type__: "Note",
      fields: [
        '<b><span style="font-weight: 400;">Electronegativity</span></b>',
        '<b><span style="font-weight: 400;">Relative measure of an atom’s ability to attract bonding electrons&nbsp;</span></b>',
      ],
      guid: "I)CC-%c0rz",
      note_model_uuid: "65b70b2f-7697-11ed-9d99-b48c9d0220f8",
      tags: [],
    },
    {
      __type__: "Note",
      fields: [
        '<b><span style="font-weight: 400;">Atomic radius</span></b>',
        '<b><span style="font-weight: 400;">Half the </span><u>shortest</u><span style="font-weight: 400;"> internuclear distance found in the structure of the element</span></b>',
      ],
      guid: "qcyth~1[(O",
      note_model_uuid: "65b70b2f-7697-11ed-9d99-b48c9d0220f8",
      tags: [],
    },
    {
      __type__: "Note",
      fields: [
        '<b><span style="font-weight: 400;">Effective nuclear charge</span></b>',
        '<b><span style="font-weight: 400;">The resultant positive charge experienced by the valence electrons in a multi-electron atom taking into consideration the shielding effect of the inner electrons.&nbsp;</span></b>',
      ],
      guid: "Fz1,Dj:#UW",
      note_model_uuid: "65b70b2f-7697-11ed-9d99-b48c9d0220f8",
      tags: [],
    },
    {
      __type__: "Note",
      fields: [
        '<b><span style="font-weight: 400;">Pi bond</span></b>',
        '<b><span style="font-weight: 400;">A pi bond is formed when two orbitals overlap side-on / collaterally&nbsp;</span></b>',
      ],
      guid: "zcYvV?Ob+W",
      note_model_uuid: "65b70b2f-7697-11ed-9d99-b48c9d0220f8",
      tags: [],
    },
    {
      __type__: "Note",
      fields: [
        '<b><span style="font-weight: 400;">Sigma bond</span></b>',
        '<b><span style="font-weight: 400;">A sigma bond is formed when two orbitals overlap head-on</span></b>',
      ],
      guid: "or]*<a,KMB",
      note_model_uuid: "65b70b2f-7697-11ed-9d99-b48c9d0220f8",
      tags: [],
    },
    {
      __type__: "Note",
      fields: [
        '<b><span style="font-weight: 400;">Conditions of ideal gas</span></b>',
        '<b><ol><li><div><span style="font-weight: 400;">Gas particles have negligible size compared to the volume of container</span></div></li><li><div><span style="font-weight: 400;">Gas particles exert negligible attractive forces on each other</span></div></li></ol></b>',
      ],
      guid: "FS+xlo33`E",
      note_model_uuid: "65b70b2f-7697-11ed-9d99-b48c9d0220f8",
      tags: [],
    },
    {
      __type__: "Note",
      fields: [
        '<b><span style="font-weight: 400;">Partial pressure</span></b>',
        '<b><span style="font-weight: 400;">The pressure that a gas in a gaseous mixture would exert as if it occupied the container alone under the same physical conditions</span></b>',
      ],
      guid: "stmZr*dO9:",
      note_model_uuid: "65b70b2f-7697-11ed-9d99-b48c9d0220f8",
      tags: [],
    },
    {
      __type__: "Note",
      fields: [
        '<b><span style="font-weight: 400;">Dalton’s Law of partial pressure</span></b>',
        '<b><span style="font-weight: 400;">The total pressure of a mixture of </span><u>non-reacting gases</u><span style="font-weight: 400;"> is equal to the sum of the partial pressures of the individual gases in the mixture</span></b>',
      ],
      guid: "x|jP$2^17?",
      note_model_uuid: "65b70b2f-7697-11ed-9d99-b48c9d0220f8",
      tags: [],
    },
    {
      __type__: "Note",
      fields: [
        '<b><span style="font-weight: 400;">Vapour pressure</span></b>',
        '<b><div><span style="font-weight: 400;">The pressure exerted by gaseous particles on the liquid surface and on the walls of the container</span></div><div><span style="font-weight: 400;">(Stronger IMFA → increasingly hard for molecules to escape from liquid surface into vapour state → lower vapour pressure)</span></div></b><br>',
      ],
      guid: "mEN8,-jM7U",
      note_model_uuid: "65b70b2f-7697-11ed-9d99-b48c9d0220f8",
      tags: [],
    },
    {
      __type__: "Note",
      fields: [
        "define mole",
        "One mole contains 6.02 x 10^23 elementary entities",
      ],
      guid: "hzefk?L!)O",
      note_model_uuid: "65bac0f7-7697-11ed-8d15-b48c9d0220f8",
      tags: [],
    },
  ],
};
